---
title: "ADSC1000_Hypothesis_Testing_II_Examples"
author: "Sean Hellingman"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Example 1 from slides

```{r}

data("iris")

t.test(iris$Sepal.Length[iris$Species == "virginica"],iris$Sepal.Length[iris$Species == "setosa"],
       alternative = "less", conf.level = 0.95, paired = FALSE, var.equal = FALSE)



```


## Example 2 from slides


```{r}

# Paired <- read.csv("Paired.csv")

# paired = TRUE
# conf.level = 0.90




```




## Example 3 from slides

```{r}

prop.test(x = c(15,35), n = c(100,110), alternative = "less", conf.level = 0.95, correct = FALSE)


```



```{r}

library(MASS)
data("Cars93")
table(Cars93$DriveTrain)

```


```{r}

x <- rnorm(50, mean = 0, sd = 2)
y <- rnorm(30, mean = 1, sd = 1)
var.test(x, y)



```


## Example 4 from slides

```{r}
set.seed(14)

x <- rnorm(57, 0, 2)
y <- rnorm(35, 1, 1)
z <- rnorm(42, 3, 1)


```


## Example 5 from slides


```{r}





```



## Example 6 from slides

```{r}

Trials <- read.csv("Trials.csv")

```



