---
title: "ADSC1000 Hypothesis Testing III Examples"
author: "Name and Student Number"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(ggplot2)

Sample1 <- rnorm(1000,mean=1,sd=2)
sample2 <- rchisq(1000,df=15)

# Normally Distributed
qqnorm(Sample1, pch = 1, frame = FALSE)
qqline(Sample1, col = "steelblue", lwd = 2)

# Not Normally Distributed
qqnorm(sample2, pch = 1, frame = FALSE)
qqline(sample2, col = "coral", lwd = 2)


Samples <- data.frame(Sample1 = Sample1, Sample2 = sample2)

ggplot(Samples, aes(sample = Sample1)) +
  stat_qq() +
  stat_qq_line()


ggplot(Samples, aes(sample = Sample2)) +
  stat_qq() +
  stat_qq_line()


```



## Example 1 from slides


```{r}

library(MASS)
data("Cars93")



```





## Example 2 from slides

```{r}

ks.test(Sample1,"pnorm")
ks.test(sample2,"pnorm")


```




# Example 3 from slides

```{r}

shapiro.test(Sample1)
shapiro.test(sample2)


```



## Example 4 from slides

```{r}

data("iris")


shapiro.test(iris$Sepal.Length[iris$Species == "setosa"])

bartlett.test(Sepal.Length ~ Species, data = iris)


```



## Example 5 from slides


```{r}

# Not independent:
chisq.test(Cars93$MPG.city,factor(Cars93$Cylinders))


```

